services:
  backend:
    build:
      context: .
      dockerfile: ./docker/dockerFile
    ports:
      - ${APP_PORT}:${APP_PORT}
    command: 'yarn dev'
    develop:
      watch:
        - path: .
          action: sync
          target: /education-backend
        - path: /package.json
          action: rebuild
    depends_on:
      - db
      - redis
  db:
    image: postgres:17
    environment:
      - POSTGRES_PASSWORD=${DB_POSTGRES_PASSWORD}
    ports:
      - ${DB_POSTGRES_PORT}:${DB_POSTGRES_PORT}
    volumes:
      - db-data:/var/lib/postgresql/data
  redis:
    image: redis:8.0
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data      

volumes:
  db-data:
  redis-data: